version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Be123123
      POSTGRES_DB: devdb
    networks:
      - nest-network
networks:
  nest-network:
